### PR TITLE
auto-blueprint-template-include

### PR DESCRIPTION
**Pull request by kellyselden**
[Rendered](https://github.com/kellyselden/ember-cli-rfcs/blob/auto-blueprint-template-include/active/0000-auto-blueprint-template-include.md)

### CODE REVIEW

**Comment by nathanhammond** [comment]
Making this a bit more concrete, the proposal is to:

MOVE FROM: https://github.com/ember-cli/ember-cli-legacy-blueprints/blob/master/blueprints/component/files/__root__/__templatepath__/__templatename__.hbs
TO: https://github.com/ember-cli/ember-cli-legacy-blueprints/blob/master/blueprints/component-template/files/__root__/__templatepath__/__templatename__.hbs

MOVE FROM: https://github.com/ember-cli/ember-cli-legacy-blueprints/blob/master/blueprints/route/files/__root__/__templatepath__/__templatename__.hbs
TO: https://github.com/ember-cli/ember-cli-legacy-blueprints/blob/master/blueprints/route-template/files/__root__/__templatepath__/__templatename__.hbs

DEPRECATE: https://github.com/ember-cli/ember-cli-legacy-blueprints/tree/master/blueprints/template

And the underlying changes that support that automatic invocation.

**Comment by nathanhammond** [comment]
@kellyselden What particular experience precipitated you opening this RFC?

This RFC allows a user to override the template without also having to reinclude the upstream JS, making it more composable. I'd call this better-factored, but rather than doing piece-wise fixes to this I'd be interested in seeing if we can come up with the "bigger picture" solution to making it easier to compose chains of blueprints. If we do this we would be making a change for this behavior and then making a change again whenever we get around to figuring out how to make blueprints play nicely together.

If those are going to be far enough apart on the timeline I don't care as it won't feel like churn. If we're aiming to do that grand rethinking soon I'd hold off on this. (Minimum one year.) We might can skirt around my churn concerns on this with changing semantics to support the module unification story.

/cc @kimroen

**Comment by kellyselden** [comment]
@nathanhammond The experience was overriding the default route blueprint, and unexpectedly having to copy over the default template blueprint to retain that functionality.

**Comment by trabus** [comment]
I really like this idea, and it would be relatively easy to implement (aside from the busy work of updating the tests). I do think we should leave the original `template` blueprint, as there is still a need to generate templates outside of the auto-generation. Furthermore, I think we can get away with extending (now that we're using core-object) the `template` blueprint for the `route-template` and `component-template` blueprints, so we won't have to maintain three different blueprints across multiple projects (ember, ember-cli-legacy-blueprints, etc).

**Comment by nathanhammond** [comment]
Per team meeting we need to:
- Include the concrete information from [this comment](https://github.com/ember-cli/rfcs/pull/59#issuecomment-230080911) into the RFC itself.
- Explore alternative solution of expanding the `template` blueprint.
- Check impact of things like `partial` on the module unification story and blueprint generation.

**Comment by kellyselden** [comment]
@nathanhammond updated per your above first two comments.

> Check impact of things like partial on the module unification story and blueprint generation.

Can you explain this more? I don't see a `partial` blueprint.

**Comment by Turbo87** [comment]
closing due to inactivity

**Pull request closed without merging**
