### PR TITLE
Include ember-cli-dependency-lint in the default app blueprint

### PR DESCRIPTION
**Pull request by dfreeman**
[Rendered](https://github.com/dfreeman/ember-cli-rfcs/blob/4b8997ffbdc23cf32aaeba860ceb8db44ea9aa1a/active/0000-dependency-lint.md)

### CODE REVIEW

**Comment by Gaurav0** [comment]
Sounds good. Can someone check if there is any performance regression? If not, I'm in favor.

**Comment by bcardarella** [comment]
Isn't this going to be resolved on its own with the new module system?

**Comment by rwjblue** [comment]
No? We aren't changing the way depedencies work with module unification...

**Comment by dfreeman** [comment]
> Can someone check if there is any performance regression?

Is there an existing test harness for verifying perf regressions in the CLI, or are you after something more ad hoc?

> Isn't this going to be resolved on its own with the new module system?

Unless I missed something major in that RFC, I don't think the new module system impacts this. Module unification doesn't change the way addon content makes its way into the build, does it? (I.e. the final build output will still only have a single copy of that addon's code)

Edit: @rwjblue beat me to the punch 🙂

**Comment by Gaurav0** [comment]
@dfreeman I mainly want to know if cold/warm/re build times don't increase significantly with the addon installed. You can benchmark simply by running ember build for cold/warm and ember serve for rebuilds. For more info, see https://github.com/ember-cli/ember-cli/blob/master/PERF_GUIDE.md

**Comment by dfreeman** [comment]
@Gaurav0 Oh I'm well familiar with that guide—just wanted to know how scientific of an answer you were looking for ;)

The addon reads one config file and writes one lint test file, and the rest is just navigating the in-memory project representation that the CLI builds itself, so perf impact should be exactly the same across cold and warm builds. The only cost on rebuild is the fs check that discovers that the tests have already been generated.

I'll double check and get some actual numbers, but my intuition is that the difference between builds with and without the addon is likely to be pretty minimal.

**Comment by dfreeman** [comment]
I did two runs each on a fresh app from CLI 2.11.1, with and without the addon. The perf differences look to be small enough to be in the noise of whatever else was happening on my machine at the time.

<table>
<tr><th></th><th colspan=2>Without the Addon</th><th colspan=2>With the Addon</th></tr>
<tr><td>Cold</td><td>7464ms</td><td>7905ms</td><td>7930ms</td><td>7746ms</td></tr>
<tr><td>Warm</td><td>1200ms</td><td>1164ms</td><td>1165ms</td><td>1156ms</td></tr>
<tr><td>Rebuild</td><td>115ms</td><td>139ms</td><td>104ms</td><td>86ms</td></tr>
</table>

**Comment by jrjohnson** [comment]
When we added this to our app we found two errors.  I found the message to be easily navigable and it was clear exactly where we needed to look in our application and in our dependency tree to find issues. 

The only way this could have been simpler or more useful is if it created the necessary addon PR on its own - but then I would probably be out of a job.  I think adding this is good for application owners and really great for the addon community in general.

**Comment by rwjblue** [comment]
I am in favor of this, and plan to bring it up at the ember-cli core team meeting today...

**Comment by stefanpenner** [comment]
it seems strange to have both this and ember-cli-dependency-checker, should they become the same thing?

**Comment by dfreeman** [comment]
@stefanpenner I have a kind of half memory of @rwjblue (or... someone?) saying in Slack that he saw them as two different things. That said, I don't feel particularly strongly either way, and the names of the two are already similar enough that it's not obvious which does what.

**Comment by kellyselden** [comment]
Agreed. Now that I think of it, those addons sound like they do the same job at face value. I vote for combination, or a name change to differentiate. something like ember-cli-addon-dependency-graph-lint (perhaps exaggerated in descriptiveness).

**Comment by jrjohnson** [comment]
They are different things - re-naming might help differentiate that.  
Combining them would make it impossible to opt out of one without losing the other so I vote for re-naming if one of these needs to happen.

_edited for clarity of opinion_

**Comment by kellyselden** [comment]
> those addons sound like they do the same job at face value

I meant the way their names read without knowing what they do.

**Comment by dfreeman** [comment]
@kellyselden `ember-cli-do-you-have-multiple-versions-of-addons-that-might-cause-problems-except-for-the-ones-where-its-okay-checker`? 😜 

I do like the idea of working the word "addon" in there somewhere though, since it doesn't actually inspect other types of dependencies.

**Comment by acorncom** [comment]
> ember-cli-do-you-have-multiple-versions-of-addons-that-might-cause-problems-except-for-the-ones-where-its-okay-checker

_Folks, I think we have a winner.  But, do you think we might hit issues with max name length on NPM?_

:trollface:

**Comment by kellyselden** [comment]
> Folks, I think we have a winner. But, do you think we might hit issues with max name length on NPM?

Forget NPM, Windows is doomed...

**Comment by rwjblue** [comment]
We are working on closing the ember-cli/rfcs repo in favor of using a single central RFC's repo for everything. This was laid out in https://emberjs.github.io/rfcs/0300-rfc-process-update.html. 

Sorry for the troubles, but would you mind reviewing to see if this is still something we need, and if so migrating this over to emberjs/rfcs?

Thank you!

**Pull request closed without merging**
