### PR TITLE
Blueprints for Embedded Applications

### PR DESCRIPTION
**Pull request by Harris-Miller**
[RFC](https://github.com/Harris-Miller/rfcs/blob/master/active/0000-blueprint-for-embedded-applications.md)

### CODE REVIEW

**Comment by csantero** [comment]
:+1:

How would this work with asset fingerprinting? When I last tried to do this, I ran into the issue that every time I built a release of the app, I would have to manually update the script tags in the hosting site's CMS to point to the new fingerprints. This was a chore and I switched to a hacky iframe solution instead.

**Comment by stefanpenner** [comment]
I actually don't believe this should be a different blueprint. It really is just another build target basically any ember app can be built to.

The approaches taken for Cordova and nw.js and electron likely make the most sense here.

It is even likely a good idea to bake in the concept of a target into cli. This would likely give common infrastructure to the above mentioned solutions.

**Comment by Harris-Miller** [comment]
@stefanpenner I like the idea of targets

`ember build`
`ember build --target embedded`
`ember build --target something-else`

Instead of having a different blueprint, just build to the intended target that the application will live in (e.g., full-site, embedded, etc...)

maybe `config/environment.js` could export `function(environment, target)` for build options
or have a `config/target.js` file specifically for that

**Comment by stefanpenner** [comment]
i think we will take approach -> https://github.com/ember-cli/rfcs/issues/26

**Comment by Harris-Miller** [comment]
:+1:

**Pull request closed without merging**
