### PR TITLE
Multiple Build Targets

### PR DESCRIPTION
**Pull request by kratiahuja**
[Rendered](https://github.com/kratiahuja/rfcs/blob/serve/active/0000-building-target-assets.md)

Due to branching issues, this is a reopen of RFC #75.

### CODE REVIEW

**Comment by les2** [comment]
@kratiahuja I have a suggestion for your consideration.

*Suggestion:* Place all targets under a common `targets/` folder (or `ember-cli-targets` if `targets/` is likely to cause problems with existing project layouts).

This would offer the following benefits:
1. Group all the targets logically together (except for the default target, which isn't part of the targets hierarchy).
2. Keep target names from conflicting with other folder names
3. Allow auto-discovery of targets by ember-cli.

Example:
```
targets/
    |
    |-- fastboot/
    |
    |-- mobile/
    |
    |-- electron/
    |
    |-- roku/
```

**Comment by les2** [comment]
Update to https://github.com/ember-cli/rfcs/pull/93#issuecomment-274283680

-  Custom `environment.js` config for a target could be located in the `targets/$name/config/environment.js` file. The inherited targets should be merged in and passed as the `defaults` parameter.

The `ember g target` command would create this file by default when generating the target.

**Comment by rwjblue** [comment]
@kratiahuja - Where are we on this? Is this still a thing that we are going to try to push forward?

**Comment by kratiahuja** [comment]
@rwjblue Not for FastBoot but I believe other platforms like electron could benefit from this. However, there is no strong usecase to build this at this time, so my recommendation is to not push forward with this.

**Comment by rwjblue** [comment]
We are working on closing the ember-cli/rfcs repo in favor of using a single central RFC's repo for everything. This was laid out in https://emberjs.github.io/rfcs/0300-rfc-process-update.html. 

Sorry for the troubles, but would you mind reviewing to see if this is still something we need, and if so migrating this over to emberjs/rfcs?

Thank you!

**Pull request closed without merging**
