### PR TITLE
Add option for JSON output to help command

### PR DESCRIPTION
**Pull request by thomassnielsen**
[Rendered markdown document](https://github.com/thomassnielsen/rfcs/blob/help-json-output/active/0000-help-json-output.md)

### CODE REVIEW

**Comment by kimroen** [comment]
I think in general that the `--json` option should be available on most–if not all–commands. For commands that return a value it can return an object directly, and for other commands (like `ember serve`) it could return a JSON Stream. ([Mocha has a JSON Stream reporter, for an example](http://mochajs.org/#json-stream-reporter)). I realize that the way addons provide output to the user is mostly ad-hoc so this could be tricky to address, but it's so much better to address it now rather than later.

**Comment by stefanpenner** [comment]
I think it's important to error if --json isn't available. Or tooling may have issues

**Comment by stefanpenner** [comment]
I'm all for defining an internal structure. Then multiple printers. Json printer, ansi color printer, text printer

**Comment by kellyselden** [comment]
I've started putting something together for this. You can see my progress [here](https://github.com/kellyselden/ember-cli/tree/json-help-output).

**Comment by stefanpenner** [comment]
@kellyselden rad.

**Comment by kellyselden** [comment]
@thomassnielsen added in #4576

**Pull request merged**
